###Todas las películas
GET http://localhost:1234/movies

###Película por ID
GET http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3

###Películas por género
GET http://localhost:1234/movies?genre=action

###Crear película
POST http://localhost:1234/movies
Content-Type: application/json

{
  "title": "The Shawshank Redemption",
  "year": 1994,
  "director": "Frank Darabont",
  "duration": 142,
  "poster": "https://i.ebayimg.com/images/g/4goAAOSwMyBe7hnQ/s-l1200.webp",
  "genre": [
    "Drama"
  ]
}
