###Todas las películas
GET http://localhost:1234/movies

###Película por ID
GET http://localhost:1234/movies/8683a844-e25d-4f0f-91d3-925f96a6af44

###Películas por género
GET http://localhost:1234/movies?genre=action

###Crear película
POST http://localhost:1234/movies
Content-Type: application/json

{
  "title": "La vita è bella",
  "year": 1997,
  "director": "roberto Benigni",
  "duration": 117,
  "poster": "https://pics.filmaffinity.com/la_vita_e_bella-646167341-large.jpg",
  "rate": 8.5,
  "genre": [
    "Drama"
  ]
}

###Borrar película
DELETE http://localhost:1234/movies/256e3cfb-eb1e-46aa-9582-8e3b7db4af2b

###Actualizar película
PATCH http://localhost:1234/movies/0a938904-93c4-4762-8f36-d6e7271a314b
Content-Type: application/json

{
  "rate": 9,
  "genre": [
    "Action"
  ]
}

### *********USERS*********

### ****AREAS****
###AREAS GET ALL
GET http://localhost:1234/areas

### AREAS CREATE
POST http://localhost:1234/areas
Content-Type: application/json

{
  "nameArea": "Internacional"
}

