### *********USERS*********

### ****AREAS****
###AREAS GET ALL
GET http://localhost:1234/areas

### AREAS CREATE
POST http://localhost:1234/areas
Content-Type: application/json

{
  "nameArea": "ONG's"
}

###AREAS DELETE
DELETE http://localhost:1234/areas/1cb6ca6b-a29a-4317-9835-f51d8d567940

###UPDATE AREA
PUT http://localhost:1234/areas/7bc65a9e-8716-4330-8a5a-f4a9e7a62b40
Content-Type: application/json

{
  "nameArea": "Hola a todos"
}

### ****REGIONS****
###REGIONS GET ALL
GET http://localhost:1234/regions

###REGIONS CREATE
POST http://localhost:1234/regions
Content-Type: application/json

{
  "nameRegion": "Oruro"
}

###REGIONS DELETE
DELETE http://localhost:1234/regions/6e4190ae-9cb8-4ba4-81a9-18b5c20e1183

###REGIONS UPDATE
PUT http://localhost:1234/regions/a5e34eb4-0119-49b8-af0b-8520964d29ba
Content-Type: application/json

{
  "nameRegion": "Santa Cruz"
}

### ****ROLES****
###ROLES GET ALL
GET http://localhost:1234/roles

###ROLES CREATE
POST http://localhost:1234/roles
Content-Type: application/json

{
  "nameRole": "tecnico"
}

###ROLES DELETE
DELETE http://localhost:1234/roles/ce1d3a13-dca1-4a36-b8fd-69cc82227ece

###ROLES UPDATE
PUT http://localhost:1234/roles/ce1d3a13-dca1-4a36-b8fd-69cc82227ece
Content-Type: application/json

{
  "nameRole": "Técnico"
}

### ****USERS****
###USERS GET ALL
GET http://localhost:1234/users

###ROLES CREATE
POST http://localhost:1234/users
Content-Type: application/json

{
  "userName": "Alejandro Cabrera",
  "userNick": "cabrera25",
  "passwordUser": "a1b2c3d4c0",
  "idArea": "dd74da3d-5330-453b-b97e-29e22196ca07",
  "idRole": "f4175392-c139-4905-b8cc-ec015968f1a0",
  "idRegion": "8fe0dbf5-4d97-4886-8fdf-4781c64e54a4"
}

###ROLES DELETE
DELETE http://localhost:1234/users/3a954f62-c563-4bc8-bc1a-3e0bff25f990

###ROLES UPDATE
PUT http://localhost:1234/users/3a954f62-c563-4bc8-bc1a-3e0bff25f990
Content-Type: application/json

{
  "userName": "Samuel Cabrera",
  "userNick": "cabrerasam",
  "passwordUser": "mi4v-aee3-5939",
  "idArea": "dd74da3d-5330-453b-b97e-29e22196ca07",
  "idRole": "f4175392-c139-4905-b8cc-ec015968f1a0",
  "idRegion": "8fe0dbf5-4d97-4886-8fdf-4781c64e54a4"
}

### *******SUBJECTS*******

### ****INDIVIDUALS****

###INDIVIDUAL GETALL
GET http://localhost:1234/individuals

###INDIVIDUAL CREATE
POST http://localhost:1234/individuals
Content-Type: application/json

{
  "nameIndividual": "Alejandro Cabrera",
  "nationalityIndividual": "Boliviano",
  "birthDateIndividual": "1984-07-07",
  "placeBirthIndividual": "La Paz",
  "genderIndividual": "Masculino",
  "maritalIndividual": "Casado",
  "photoIndividual": "http://ruta.foto",
  "partyIndividual": "MAS",
  "workIndividual": "Programador",
  "educationIndividual": "Lic.",
  "emailIndividual": "alcazar.samuel@gmail.com",
  "phoneIndividual": "67100787",
  "networksIndividual": {
    "facebook": "https://facebook.com",
    "x": "https://x.com"
  },
  "idUser": "d6b6fdc4-e0a2-4558-9cc0-3f2cf3c4c698"
}

###INDIVIDUAL DELETE
DELETE http://localhost:1234/individuals/89531733-5541-4f1b-951b-828d0cd5c60a

###INDIVIDUAL UPDATE
PUT http://localhost:1234/individuals/89531733-5541-4f1b-951b-828d0cd5c60a
Content-Type: application/json

{
  "nameIndividual": "Alejandro Samuel Cabrera",
  "nationalityIndividual": "Boliviano",
  "birthDateIndividual": "1984-07-07",
  "placeBirthIndividual": "El Alto",
  "genderIndividual": "Masculino",
  "maritalIndividual": "Casado",
  "photoIndividual": "http://ruta.foto",
  "partyIndividual": "MAS",
  "workIndividual": "Programador",
  "educationIndividual": "Lic.",
  "emailIndividual": "alcazar.samuel@gmail.com",
  "phoneIndividual": "67100787",
  "networksIndividual": {
    "facebook": "https://facebook.com",
    "x": "https://x.com"
  },
  "idUser": "d6b6fdc4-e0a2-4558-9cc0-3f2cf3c4c698"
}

###COLLECTIVES

###COLLECTIVE GETALL
GET http://localhost:1234/collectives

###COLLECTIVE CREATE
POST http://localhost:1234/collectives
Content-Type: application/json

{
  "nameCollective": "CEADL",
  "originCollective": "Nacional",
  "typeCollective": "ONG",
  "headquartersCollective": "El Alto",
  "descriptionCollective": "En la actualidad el CEADL, es una creación colectiva de grupos de jóvenes y profesionales.",
  "missionCollective": "Fortalecemos personas y organizaciones sociales en sus capacidades participativas y de incidencia para construir una cultura e institucionalidad democrática en el Estado y la sociedad civil, precautelando el ejercicio pleno de los Derechos Humanos y Ciudadanos a nivel local y nacional, en el marco de los Objetivos de Desarrollo Sostenible.",
  "visionCollective": "Personas individuales y organizaciones de la sociedad civil, con énfasis en las juventudes, mujeres y pueblos indígenas, participan de forma organizada, democrática y equitativa en diversos espacios sociopolíticos para la reivindicación y el ejercicio pleno de sus Derechos Humanos y Ciudadanos.",
  "networkCollective": {
    "facebook": "https://facebook.com/ceadl",
    "x": "https://x.com/ceadl"
  },
  "infAreaCollective": "",
  "financingCollective": "",
  "personalCollective": {
    "director": "Juan Carlos Balderas",
    "técnico": "Joel Ibarra Batallanos"
  },
  "idUser": "d6b6fdc4-e0a2-4558-9cc0-3f2cf3c4c698"
}

###INDIVIDUAL DELETE
DELETE http://localhost:1234/individuals/89531733-5541-4f1b-951b-828d0cd5c60a

###INDIVIDUAL UPDATE
PUT http://localhost:1234/individuals/89531733-5541-4f1b-951b-828d0cd5c60a
Content-Type: application/json

{
  "nameCollective": "",
  "originCollective": "",
  "typeCollective": "",
  "headquartersCollective": "",
  "descriptionCollective": "",
  "missionCollective": "",
  "visionCollective": "",
  "networkCollective": "",
  "infAreaCollective": "",
  "financingCollective": "",
  "personalCollective": "",
  "idUser": "d6b6fdc4-e0a2-4558-9cc0-3f2cf3c4c698"
}